version: '3.8'
services:
  NoteApp:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: piotrwrbl/noteapp:latest
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    command: npm start


  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
